[phases.setup]
commands = [
  "pip install -r backend/requirements.txt"
]

[phases.build]
commands = [
  "python backend/manage.py collectstatic --noinput"
]

[phases.start]
commands = [
  "python backend/manage.py migrate",
  "gunicorn backend.schuffle.wsgi:application --bind 0.0.0.0:$PORT"
]
